theme:
  switch: true
  default: style-light
# 语言
language: zh-Hans
# 网站图标Favicon
favicon:
  logo: /img/favicon.svg
  icon16: /img/favicon.svg
  icon32: /img/favicon.svg
  visibilitychange: true

#用户信息
user:
  name: 张鱼锅巴
  first_name: 锅巴
  last_name: 张鱼
  avatar: /img/avatar.jpg
  describe: 云卷云舒

# The icon used by the theme
icons:
  sun: far fa-sun
  moon: far fa-moon
  play: fas fa-play
  email: far fa-envelope
  next: fas fa-arrow-right
  calendar: far fa-calendar-alt
  clock: far fa-clock
  user: far fa-user
  back_top: fas fa-arrow-up
  close: fas fa-times
  search: fas fa-search
  reward: fas fa-hand-holding-usd
  user_tag: fas fa-user-alt
  toc_tag: fas fa-th-list
  read: fas fa-book-reader
  arrows: fas fa-arrows-alt-h
  double_arrows: fas fa-angle-double-down
  copy: fas fa-copy

# logo

top_bars:
  - title: 首页
    url: /
  - title: 进化之路
    url: /archives/
  - title: Link
    url: /links/
  - title: About
    url: /about/
  - title: 黑科技
    url: /customize_page/
  - title: 相册
    url: /gallery/

sidebar:
  typedTextPrefix: 2023
  typedText: ["万事胜意"]
  info: # 个人信息
    - key: 地址
      val: 安徽
    - key: 年龄
      val: 18 forever
    - key: Hobby
      val: 美食与宅与play
    - key: 才华
      val: 才高八斗,共有八百斗!!

  social:
    - icon: fab fa-github
      url: https://github.com/MaLuns/Hexo-theme-async
      name: Github

banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Welcome to my World!

footer:
  powered:
    enable: true
  beian:
    enable: false
    icp:
  copyrightYear: 2022
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 2022/04/10 17:00:00
  custom_text:

search:
  enable: true
  type: local
  preload: true
  trigger: auto

baidu_push: true

creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true

swup: true

toc:
  enable: true
  list_number: false
  max_depth: 3
  min_depth: 1

rightside:
  readmode: true
  aside: true

post_pagination:
  enable: true
  type: small

highlight:
  title: mac
  height_limit: 200

cover:
  default:
    - /img/block.jpg
    - https://th.wallhaven.cc/orig/wq/wqvkl7.jpg
    - https://th.wallhaven.cc/orig/rd/rdq3v1.jpg
    - https://th.wallhaven.cc/orig/rd/rd183j.jpg
    - https://th.wallhaven.cc/orig/q2/q287wd.jpg
    - https://th.wallhaven.cc/orig/g7/g79ov3.jpg
    - https://th.wallhaven.cc/orig/q2/q2mkzr.jpg
    - https://th.wallhaven.cc/orig/v9/v9j3yp.jpg
    - https://th.wallhaven.cc/orig/y8/y8yvzx.jpg
    - https://th.wallhaven.cc/orig/1k/1kdw2w.jpg
    - https://th.wallhaven.cc/orig/57/57jqk1.jpg
    - https://th.wallhaven.cc/orig/57/5762p1.jpg
    - https://th.wallhaven.cc/orig/j3/j3zo1y.jpg
    - https://th.wallhaven.cc/orig/m9/m9gkky.jpg
    - https://th.wallhaven.cc/orig/e7/e7kv9k.jpg
    - https://th.wallhaven.cc/orig/ym/ym9ldk.jpg
    - https://th.wallhaven.cc/orig/pk/pk5259.jpg
    - https://th.wallhaven.cc/orig/8o/8opxpk.jpg
    - https://th.wallhaven.cc/orig/k7/k7yog7.jpg
    - https://th.wallhaven.cc/orig/v9/v93zv3.jpg
    - https://th.wallhaven.cc/orig/wq/wqj65q.jpg
    - https://th.wallhaven.cc/orig/p9/p9kg1m.jpg
    - https://th.wallhaven.cc/orig/8o/8o9vw1.jpg
    - https://th.wallhaven.cc/orig/x8/x8yy3o.jpg
  type: random
