theme:
  default: style-light
# 语言
language: zh-Hans
# 网站图标Favicon
favicon:
  logo: /img/favicon.svg
  icon16: favicon-16x16.png
  icon32: favicon-32x32.png
  visibilitychange: true

#用户信息
user:
  name: 张鱼锅巴
  first_name: 锅巴
  last_name: 张鱼
  email: 1120306825@qq.com
  avatar: /img/avatar.jpg
  domain: https://1999zaz.github.io
  describe: 云卷云舒,
  birthDay: 07/09/1999
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上,部署HTTPS。

# The icon used by the theme
icons:
  sun: far fa-sun
  moon: far fa-moon
  play: fas fa-play
  email: far fa-envelope
  next: fas fa-arrow-right
  calendar: far fa-calendar-alt
  clock: far fa-clock
  user: far fa-user
  back_top: fas fa-arrow-up
  close: fas fa-times
  search: fas fa-search
  reward: fas fa-hand-holding-usd
  user_tag: fas fa-user-alt
  toc_tag: fas fa-th-list
  read: fas fa-book-reader
  arrows: fas fa-arrows-alt-h
  double_arrows: fas fa-angle-double-down
  copy: fas fa-copy

# logo

top_bars:
  - title: Home
    url: /
  - title: 🌞光荣进化
    url: /archives/
  - title: 🎃Link
    url: /links/
  - title: 🤸About
    url: /about/
  - title: 📸相册
    url: /gallery/

sidebar:
  typedTextPrefix: 2023
  typedText: ["万事胜意"]
  info: # 个人信息
    - key: 地址
      val: 安徽
    - key: 年龄
      val: 18 forever
    - key: Hobby
      val: 美食与宅与play
    - key: 才华
      val: 才高八斗,共有八百斗!!

  social:
    - icon: fab fa-github
      url: https://github.com/1999zaz
      name: Github
    - icon: fab fa-alipay
      name: Alipay
    - icon: fab fa-weixin
      name: Weixin
banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 我见山河涌 似是故人来
    bannerText: Welcome to my World!
  archive:
    bgurl: https://images.pexels.com/photos/14530150/pexels-photo-14530150.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1
    bannerTitle: 这路遥马急的人间<br>⏳⏳⏳⏳⏳⏳
    bannerText: The article archive
  links:
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 这是我的益达 <br>不!是你的益达
    bannerText: Between u and m
  about:
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 你的...<br>头发乱了
    bannerText: About me

footer:
  powered:
    enable: true
  beian:
    enable: false
    icp:
  copyrightYear: 2022
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 2022/04/10 17:00:00
  custom_text:

search:
  enable: true
  type: local
  preload: true
  trigger: auto

baidu_push: true

creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true

swup: true

toc:
  enable: true
  list_number: false
  max_depth: 3
  min_depth: 1

rightside:
  readmode: true
  aside: true

post_pagination:
  enable: true
  type: small

highlight:
  title: mac
  height_limit: 200

cover:
  default:
    - /img/block.jpg
  type: random

categorie_card:
  enable: true
  len: 2
  list: ["生活记录", "学习之路"]
